# Generated by Django 3.1.7 on 2021-04-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='delta',
            field=models.IntegerField(default=0, verbose_name='delta'),
            preserve_default=False,
        ),
    ]
