# Generated by Django 3.1.7 on 2021-04-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_useractivity_delta'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
